"""
    LABEL INFOS PERSO
"""
TM_JOUEUR_NOM_COMPLET_LABEL_TEXT = 'Nom'
TM_JOUEUR_NAISSANCE_LABEL_TEXT = 'Date de naissance'
TM_JOUEUR_TAILLE_LABEL_TEXT = 'Taille'
TM_JOUEUR_NATIONALITES_LABEL_TEXT = 'Nationalité'
TM_JOUEUR_PIED_FORT_LABEL_TEXT = 'Pied'
TM_JOUEUR_EQUIPEMENTIER_LABEL_TEXT = 'Équipementier'
TM_JOUEUR_PRETE_DATE_FIN_CONTRAT_ACTUEL_LABEL_TEXT = 'En contrat là-bas'
TM_JOUEUR_DATE_FIN_CONTRAT_ACTUEL_LABEL_TEXT = 'Contrat jusqu’à'