"""
    URL PAGE MOTS CLEFS
"""
TM_URL = "https://www.transfermarkt.fr"
TM_URL_TRANSFERTS = "transfers"
TM_URL_REPLACE = "{page_transfermarkt}"
TM_URL_INFO_CLUB = "datenfakten"
TM_URL_INFO_STADE_CLUB = "stadion"

"""
    LABEL INFOS PERSO
"""
TM_JOUEUR_NOM_COMPLET_LABEL_TEXT = 'Nom'
TM_JOUEUR_NAISSANCE_LABEL_TEXT = 'Date de naissance'
TM_JOUEUR_TAILLE_LABEL_TEXT = 'Taille'
TM_JOUEUR_NATIONALITES_LABEL_TEXT = 'Nationalité'
TM_JOUEUR_PIED_FORT_LABEL_TEXT = 'Pied'
TM_JOUEUR_EQUIPEMENTIER_LABEL_TEXT = 'Équipementier'
TM_JOUEUR_PRETE_DATE_FIN_CONTRAT_ACTUEL_LABEL_TEXT = 'En contrat là-bas'
TM_JOUEUR_DATE_FIN_CONTRAT_ACTUEL_LABEL_TEXT = 'Contrat jusqu’à'

"""
    TRANSFERTS
"""
TM_HISTORIQUE_TRANSFERT_FIND = "Historique des transferts"
TM_CLASS_TRANSFERT_LIGNE = "tm-player-transfer-history-grid"

TM_CLASS_TRANSFERT_LIGNE_DATE = TM_CLASS_TRANSFERT_LIGNE + "__date"
TM_CLASS_TRANSFERT_LIGNE_CLUB_DEPART = TM_CLASS_TRANSFERT_LIGNE + "__old-club"
TM_CLASS_TRANSFERT_LIGNE_CLUB_ARRIVEE = TM_CLASS_TRANSFERT_LIGNE + "__new-club"
TM_CLASS_TRANSFERT_LIGNE_MONTANT = TM_CLASS_TRANSFERT_LIGNE + "__fee"

TM_LIBELLE_FIN_CARRIERE = "Fin de carrière"
TM_LIBELLE_PAUSE_CARRIERE = "Pause carrière"
TM_LIBELLE_FIN_DE_PRET = "Fin du prêt"
TM_LIBELLE_TRANSFERT_LIBRE = "Tr. libre"
TM_LIBELLE_PAS_DE_MOUVEMENT = "-"


"""
    INFOS CLUB
"""
TM_BOX_INFO_CLUB = "Informations et faits"
TM_BOX_INFO_NOM_CLUB = "Nom officiel du club"
TM_BOX_INFO_ADRESSE_CLUB = "Adresse"
TM_BOX_INFO_SITE_CLUB = "Page d'accueil"
TM_BOX_INFO_CREATION_CLUB = "Fondation"
TM_BOX_INFO_COULEURS_CLUB = "Couleurs de club"
TM_BOX_INFO_LOGOS_CLUB = "Tous les sommets historiques"

"""
    INFOS STADE
"""
TM_LIBELLE_NOM_STADE = "Nom du stade"
TM_LIBELLE_CAPACITE_STADE = "Capacité totale"
TM_LIBELLE_CONSTRUCTION_STADE = "Date de construction"
TM_LIBELLE_BOX_ADRESSE_STADE = "Contact"
TM_LIBELLE_ADRESSE_STADE = "Adresse"
