API_LOGIN = "xxx"
API_PASSWD = "xxx"

METHOD_POST = "POST"
METHOD_GET = "GET"
METHOD_PUT = "PUT"
METHOD_PATCH = "PATCH"

API_BASE_URL = "http://api/api"
API_URL_LOGIN = f"{API_BASE_URL}/login"
API_URL_GET_JOUEUR_BY_ID_TM = f"{API_BASE_URL}/joueur/transfermarkt"
API_URL_GET_PAYS_BY_NOM_FR = f"{API_BASE_URL}/pays/byNom"
API_URL_PAYS = f"{API_BASE_URL}/pays"
API_URL_GET_POSTE_BY_ID_TM = f"{API_BASE_URL}/poste/transfermarkt"
