resources:
  App\Entity\Club:
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters: ["club.id_transfermarkt_filter"]
        normalizationContext:
          groups: ["read.Club"]
        openapi:
          summary: Retrouve les club
          description: ^
            Retrouve les clubs
          parameters:
            - in: query
              name: id_transfermarkt
              schema:
                type: integer
              required: false
              description: ID TransferMarkt du club
      ApiPlatform\Metadata\Post:
        denormalizationContext:
          groups: ["persist.Club"]
        security: 'is_granted("ROLE_SCRAPP")'
