resources:
    App\Entity\Joueur:
        operations:
            ApiPlatform\Metadata\Post:
                denormalizationContext:
                    groups: ["persist.Joueur"]
                security: 'is_granted("ROLE_SCRAPP")'
                openapi:
                    summary: Sauvegarde un joueur
                    description: Sauvegarde un joueur
            ApiPlatform\Metadata\GetCollection:
                filters: ["joueur.id_transfermarkt_filter"]
                normalizationContext:
                groups: ["read.Joueur"]
                openapi:
                summary: Retrouve les joueurs
                description: ^
                    Retrouve les joueurs
                parameters:
                    - in: query
                      name: id_transfermarkt
                      schema:
                          type: integer
                      required: false
                      description: ID TransferMarkt du joueur
