resources:
    App\Entity\Pays:
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters: ["pays.by_name"]
                normalizationContext:
                    groups: ["read.Pays"]
                openapi:
                    summary: Retrouve un pays via son nom français
                    description: ^
                        Retrouve un pays via son nom français
                    parameters:
                        - in: query
                          name: nom_fr
                          schema:
                              type: string
                          required: false
                          description: Nom français du pays
            ApiPlatform\Metadata\Post:
                normalizationContext:
                    groups: ["persist.Pays"]
                security: 'is_granted("ROLE_BEPO")'
            ApiPlatform\Metadata\Patch:
                security: 'is_granted("ROLE_BEPO")'
