resources:
  App\Entity\Pays:
    collectionOperations:
      get: ~
      init:
        method: POST
        path: /pays/init
        controller: App\Controller\Administration\PaysController::initPays
        read: false
        normalization_context:
          groups: ['read.Pays']
        security : 'is_granted("ROLE_ADMIN")'
      post:
        security: 'is_granted("ROLE_ADMIN")'
    itemOperations:
      get: ~
  App\Entity\Club:
    collectionOperations:
      scrapp:
        method: POST
        path: /club/scrapp
        controller: App\Controller\Administration\ScrappController::scrappJoueursEtClubs
        validate: false
        normalization_context:
          groups: ['read.Club']
      save_scrapp:
        method: POST
        path: /club/save_scrapp
        controller: App\Controller\Administration\ScrappController::saveScrappJoueursEtClubs
        validate: false
        normalization_context:
          groups: ['read.Club']
    itemOperations:
      get: ~
  App\Entity\RencontreLigue1:
    collectionOperations:
      scrapp:
        method: POST
        path: /rencontre_ligue1/scrapp
        controller: App\Controller\Administration\ScrappController::scrappMatchsLigue1
        validate: false
        normalization_context:
          groups: ['read.RencontreLigue1']
    itemOperations:
      get: ~
